# Expanding Your Dashboard 

## Cancer mortality data

If you have cancer mortality data, CaRDO will add a mortality statistics page to your dashboard. The data requirements and processes for loading cancer mortality data are identical to those we’ve described for cancer incidence data.

1.	You must have a single column for each variable and outcome you wish to report, and each row in your dataset should correspond to a unique combination of each variable.
2.	Cancer-type values must be coded as you wish them to be displayed
3.	Cancer deaths must be aggregated by 5-year age groups, with age groups coded numerically from 1 – 18.

The interface will ask you to load in a cancer incidence and mortality file separately. However, whether you store mortality data in a separate data file, or as an additional column in your incidence data file (and load the file twice) does not matter. 

## Age-standardised rates – population data 

If you wish to report age-standardised cancer rates, you must provide a population file that corresponds to your registry or organisation’s catchment area. Population data should be organised by year, 5-year age groups and sex, and otherwise be structured the same as your incidence data. See the example below (variable names do not matter). 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Create a data frame
population_data <- data.frame(
  "Year" = c(2003,2004,2005,2006,2007),
  "Sex" = c(2,1,2,2,1),
  "Age.group" = c(1,1,3,6,11),
  "Population" = c(6332,7541,8544,9198,12632)
)

# Create the table
kbl(population_data) %>%
  kable_styling(bootstrap_options =c("condensed","striped"), full_width = T, font_size = 14) 
  #add_header_above(c("Table 1. Example incidence data set"= 1, " " = 2, "Mortality (a)" = 2), font_size = 14)
```

<br>
CaRDO will calculate age-standardised rates using a standard population that you will specify from a list of options. If your preferred standard population is not available, you will have the option to load your own.  

## Other data details to note
1. As with incidence and mortality, it is not necessary that your population file contains population data for persons (sex = 3). 
2. Rates will be suppressed where low count data has been suppressed.

